import { Tradition } from '@/types';

export const TRADITIONS: Tradition[] = [
  'Ashanti/Akan',
  'Yoruba',
  'Zulu',
  'Nubian',
  'Dogon',
  'Kikuyu',
  'Swahili',
  'Khoisan',
  'Pan-African',
];

export const MAIN_GENRES = [
  "Romance",
  "Fantasy",
  "Science Fiction",
  "Afrofuturism",
  "African Mythology & Folklore",
  "Thriller",
  "Mystery",
  "Horror",
  "Drama",
  "Action",
  "Adventure",
  "Crime",
  "Historical Fiction",
  "Literary Fiction",
  "Young Adult",
  "New Adult",
  "Children’s Fiction",
  "Dystopian",
  "Contemporary Fiction",
  "Epic",
  "Short Stories",
  "Poetry",
  "Fan Fiction",
  "Paranormal",
  "Western",
];

export const SUB_GENRES = [
  "Romance",
  "Contemporary Romance",
  "Dark Romance",
  "Paranormal Romance",
  "Historical Romance",
  "LGBTQ+",
  "Fantasy",
  "Magical Realism",
  "Science Fiction",
  "Psychological Thriller",
  "Crime Thriller",
  "Political Thriller",
  "Espionage Thriller",
  "Detective Mystery",
  "Modern Mystery",
  "Murder Mystery",
  "Locked-Room Mystery",
  "Psychological Horror",
  "Folk Horror",
  "Gothic Horror",
  "Body Horror",
  "Occult Horror",
  "Family Drama",
  "Psychological Drama",
  "Social Drama",
  "Political Drama",
  "Military",
  "Martial Arts",
  "Adventure",
  "Organized Crime",
  "True Crime",
  "Historical Fiction",
  "Literary Fiction",
  "Contemporary Fiction",
  "Epic",
  "Saga",
  "Generational Saga",
  "Dystopian",
  "Supernatural",
  "Vampire",
  "Werewolf",
  "Witches",
  "Ghosts",
  "Demons",
];

export const TRIGGER_WARNINGS = [
  "Violence",
  "Gore / Graphic Violence",
  "Blood",
  "Death",
  "Murder",
  "Suicide",
  "Self-Harm",
  "Sexual Assault",
  "Rape",
  "Sexual Violence",
  "Child Abuse",
  "Domestic Abuse",
  "Physical Abuse",
  "Emotional/Psychological Abuse",
  "Torture",
  "Kidnapping",
  "Human Trafficking",
  "Drug Use / Addiction",
  "Alcoholism",
  "Eating Disorders",
  "Pregnancy / Miscarriage",
  "Infertility",
  "Grief / Loss",
  "Mental Illness",
  "Panic Attacks / Anxiety",
  "Trauma / PTSD",
  "Abuse of Animals",
  "War / Conflict",
  "Religious Trauma",
  "Racism / Discrimination",
  "Homophobia / LGBTQ+ Discrimination",
  "Child Death",
  "Death of a Parent / Loved One",
  "Explicit Sexual Content",
  "Sexual Harassment",
  "Stalking",
  "Body Horror",
  "Cannibalism",
  "Cults / Religious Extremism",
  "Slavery",
  "Others",
];

export const GENRES = MAIN_GENRES.map((g) => ({
  id: g.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  label: g,
  icon: 'BookOpen',
}));
