import { Story, UserProfile, SavedQuote, ReadingProgress } from '@/types';

export const MOCK_STORIES: Story[] = [
  {
    id: "anansi-and-the-pot-of-wisdom",
    slug: "anansi-and-the-pot-of-wisdom",
    aliases: ["hr-4", "hr-1", "anansi-1"],
    title: "Anansi and the Pot of Wisdom",
    subtitle: "The Trickster's Folly in the High Baobab",
    synopsis: "When Kweku Anansi attempts to hoard all knowledge in the world within a clay pot, his pride is put to the test before the watchful eyes of the sky god Nyame.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    tradition: "Ashanti/Akan",
    mainGenre: "Trickster Lore",
    subGenres: ["Moral Philosophy", "Mythology", "Fables"],
    tags: ["Anansi", "Wisdom", "Baobab", "SkyGod", "Akan"],
    difficulty: "Beginner",
    status: "completed",
    authorId: "user-kwame-01",
    authorName: "Kwame Asante",
    authorPenName: "Kwame of Ashanti",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
    authorBio: "Keeper of Ashanti trickster lore and ancient Dogon constellation myths. Author of 12 living folklore manuscripts.",
    publishedAt: "Jan 10, 2026",
    updatedAt: "Feb 02, 2026",
    estimatedReadTime: 12,
    totalChapters: 3,
    totalBranches: 14,
    readsCount: 38420,
    likesCount: 2840,
    bookmarksCount: 940,
    favoritesCount: 1250,
    commentsCount: 142,
    isFeatured: true,
    isRecentlyUpdated: false,
    isNewRelease: false,
    isInteractive: true,
    hasAudioNarration: true,
    chapters: [
      {
        id: "chap-1",
        number: 1,
        title: "The Calabash of All Wisdom",
        summary: "Anansi visits the sky god Nyame to purchase all the wisdom of the earth in a clay pot.",
        readTimeMinutes: 4,
        status: "published",
        likesCount: 820,
        commentsCount: 45,
        updatedAt: "2026-01-10",
        rootNodeId: "node-1",
        nodes: {
          "node-1": {
            id: "node-1",
            title: "Nyame's Golden Throne",
            content: `In the celestial court above the clouds of Asase Yaa, Nyame the Sky God looked down upon Kwaku Anansi with amused eyes.

"You ask for that which cannot be contained, little weaver," Nyame spoke, his voice echoing like rolling thunder across the canopy. "All the wisdom in the heavens and earth resides in this clay pot. Guard it with humility, or its weight will scatter upon the four winds."

Anansi bowed low, clasping the heavy clay pot to his chest with eight trembling legs.`,
            choices: [
              {
                id: "choice-1a",
                label: "Pledge to share the calabash with the village elders",
                targetNodeId: "node-2a",
                consequenceHint: "Honors communal traditions and gains elder blessings...",
              },
              {
                id: "choice-1b",
                label: "Hurry down to the forest to hoard the knowledge for yourself",
                targetNodeId: "node-2b",
                consequenceHint: "Fosters secret pride and stirs the spirits of the deep bush...",
              },
            ],
          },
          "node-2a": {
            id: "node-2a",
            title: "The Village Gathering",
            content: `The elders beneath the shade of the sacred silk-cotton tree welcomed Anansi with song and praise. Yet within the spider's heart, a seed of covetousness began to sprout.

"Why should I part with the sky god's greatest treasure?" Anansi whispered to his reflection in the river.`,
            choices: [
              {
                id: "choice-2a1",
                label: "Flee into the deep baobab forest under cover of moonlight",
                targetNodeId: "node-3",
                consequenceHint: "Leads to the fateful climb...",
              },
            ],
          },
          "node-2b": {
            id: "node-2b",
            title: "The Solitary Baobab",
            content: `Anansi slipped into the deepest hollows of the forest. The giant Baobab tree stood before him like an ancient sentinel, reaching toward the clouds.

"Here," Anansi chuckled greedily, "atop this tree no mortal or beast shall ever steal my wisdom."`,
            choices: [
              {
                id: "choice-2b1",
                label: "Tie the pot to your belly and begin the ascent",
                targetNodeId: "node-3",
                consequenceHint: "The clay pot blocks your forward reach...",
              },
            ],
          },
          "node-3": {
            id: "node-3",
            title: "The Struggle at the Canopy",
            content: `With the wide clay pot tied firmly against his belly, Anansi could not get close enough to hug the tree trunk. He slipped and clawed, growing ever more frustrated with every branch.

From the underbrush below, his young son Ntikuma watched and giggled softly.

"Father," Ntikuma called out, "would it not be wiser to tie the pot to your back so your arms and legs may freely grip the trunk?"`,
            choices: [
              {
                id: "choice-3a",
                label: "Listen humbly to Ntikuma's child wisdom and shift the pot",
                targetNodeId: "node-4a",
                consequenceHint: "Wisdom through humility brings victory...",
              },
              {
                id: "choice-3b",
                label: "Fly into a rage that a child has surpassed your gathered knowledge",
                targetNodeId: "node-4b",
                consequenceHint: "Pride precipitates the great shattering...",
              },
            ],
          },
          "node-4a": {
            id: "node-4a",
            title: "The Triumph of Humility",
            content: `Anansi paused, humbled by his son's simple logic. He shifted the calabash to his back and scaled the tree with ease.

Realizing that wisdom cannot be hoarded in a pot when even a child possessed insight he lacked, Anansi opened the calabash from the tree crown, gently releasing streams of golden light to touch every corner of the earth.`,
            choices: [],
            isEnding: true,
            endingType: "triumph",
            moralLesson: "True wisdom is communal; no single creature can claim its entirety.",
          },
          "node-4b": {
            id: "node-4b",
            title: "The Shattered Pot",
            content: `Enraged that he possessed the 'pot of all wisdom' yet had less practical sense than his young child, Anansi hurled the calabash to the ground in fury.

The clay pot smashed against the river stones with a sound like thunder. A great whirlwind swept the scattered shards, blowing sparks of wisdom into every river, village, and wandering soul on earth.`,
            choices: [],
            isEnding: true,
            endingType: "lesson",
            moralLesson: "Pride shatters what humility was meant to preserve.",
          },
        },
      },
      {
        id: "chap-2",
        number: 2,
        title: "The Spider and the Whispering River",
        summary: "Seeking to recover the scattered wisdom, Anansi strikes an alliance with the River Spirit.",
        readTimeMinutes: 5,
        status: "published",
        likesCount: 610,
        commentsCount: 28,
        updatedAt: "2026-01-18",
        rootNodeId: "node-c2-1",
        nodes: {
          "node-c2-1": {
            id: "node-c2-1",
            title: "The Waters of Bosomtwe",
            content: `Beside the glowing waters of Lake Bosomtwe, Anansi spun a silver net across the reeds. The water ripples formed shapes of dancing maidens as the River Spirit emerged.`,
            choices: [
              {
                id: "choice-c2-1",
                label: "Offer the River Spirit sweet yam flour in exchange for guidance",
                targetNodeId: "node-c2-end",
                consequenceHint: "Gains the water blessing...",
              },
            ],
          },
          "node-c2-end": {
            id: "node-c2-end",
            title: "The River's Secret",
            content: `The River Spirit smiled. "Wisdom is like water, Kwaku—it nourishes only when it flows freely."`,
            choices: [],
            isEnding: true,
            endingType: "lesson",
          },
        },
      },
      {
        id: "chap-3",
        number: 3,
        title: "The Council of the Four Winds",
        summary: "The final covenant between humanity, nature, and the heavens.",
        readTimeMinutes: 3,
        status: "published",
        likesCount: 490,
        commentsCount: 19,
        updatedAt: "2026-02-02",
        rootNodeId: "node-c3-1",
        nodes: {
          "node-c3-1": {
            id: "node-c3-1",
            title: "The Golden Web in the Clouds",
            content: `Anansi returned to the celestial sphere, weaving a great web between the earth and stars to ensure storytelling would live on forever in every hearth and campfire.`,
            choices: [],
            isEnding: true,
            endingType: "triumph",
          },
        },
      },
    ],
  },
  {
    id: "sundiata-the-lion-king-of-mali",
    slug: "sundiata-the-lion-king-of-mali",
    aliases: ["hr-2", "sundiata-1"],
    title: "Sundiata: The Lion King of Mali",
    subtitle: "The Epic Rise of the Mandinka Empire",
    synopsis: "Born unable to walk, young Sundiata Keita rises through prophecy, iron will, and sacred sorcery to unite the twelve kingdoms against the ruthless sorcerer-king Soumaoro Kanté.",
    coverImage: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?q=80&w=800&auto=format&fit=crop",
    tradition: "Pan-African",
    mainGenre: "Historical Epics",
    subGenres: ["Military Strategy", "Royal Dynasties", "Heroic Quest"],
    tags: ["Sundiata", "Mali", "LionKing", "Balla", "Mandinka"],
    difficulty: "Elderly / Complex",
    status: "ongoing",
    authorId: "user-amina-02",
    authorName: "Amina Diallo",
    authorPenName: "Amina of Djenné",
    authorAvatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=200&auto=format&fit=crop",
    authorBio: "Historian of the Western Sahel and oral performer preserving epic Manden poetry.",
    publishedAt: "Feb 14, 2026",
    updatedAt: "Feb 28, 2026",
    estimatedReadTime: 25,
    totalChapters: 5,
    totalBranches: 22,
    readsCount: 24800,
    likesCount: 1920,
    bookmarksCount: 810,
    favoritesCount: 970,
    commentsCount: 96,
    isFeatured: true,
    isRecentlyUpdated: true,
    isNewRelease: false,
    isInteractive: true,
    hasAudioNarration: true,
    chapters: [
      {
        id: "sun-chap-1",
        number: 1,
        title: "The Iron Rod of Niani",
        summary: "Sundiata overcomes childhood infirmity to stand upon his feet for his mother Sogolon.",
        readTimeMinutes: 6,
        status: "published",
        likesCount: 540,
        updatedAt: "2026-02-14",
        rootNodeId: "sun-node-1",
        nodes: {
          "sun-node-1": {
            id: "sun-node-1",
            title: "Sogolon's Tears",
            content: `The cruel first wife Sassouma Bereté mocked Sogolon Kedjou in the palace courtyard. Young Sundiata, crawling upon the red earth, felt the burning sting of his mother's dishonor.

"Fetch the master blacksmiths!" Sundiata ordered the court advisor Balla Fasséké. "Bring me an iron rod as heavy as the mountains of Manden!"`,
            choices: [
              {
                id: "sun-c1",
                label: "Call upon the protective totem spirits of the Buffalo of Do",
                targetNodeId: "sun-node-2",
                consequenceHint: "Awakens the ancestral roar inside your veins...",
              },
            ],
          },
          "sun-node-2": {
            id: "sun-node-2",
            title: "The Baobab Uprooted",
            content: `With a mighty roar that shook the palace walls, Sundiata pressed down upon the heavy iron rod. The iron bent like a reed as the boy stood upright for the very first time! He marched into the forest, uprooted an entire baobab tree by its roots, and laid it at his mother's feet.`,
            choices: [],
            isEnding: true,
            endingType: "triumph",
          },
        },
      },
    ],
  },
  {
    id: "mami-wata-whispering-currents",
    slug: "mami-wata-whispering-currents",
    aliases: ["hr-3", "mami-1"],
    title: "Mami Wata: Whispering Currents",
    subtitle: "The Sacred Guardian of the Deep Delta",
    synopsis: "A young fisherman caught in the tempest of the Guinea Coast is taken into the underwater coral palaces of Mami Wata, where he must choose between boundless wealth and moral honor.",
    coverImage: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?q=80&w=800&auto=format&fit=crop",
    tradition: "Yoruba",
    mainGenre: "Spiritual Lore",
    subGenres: ["Ocean Mysteries", "FolkloreEthics", "African Pantheon"],
    tags: ["MamiWata", "Ocean", "Delta", "Orisha", "Yoruba"],
    difficulty: "Intermediate",
    status: "ongoing",
    authorId: "user-adebayo-03",
    authorName: "Chief Adebayo",
    authorPenName: "Adebayo Olawale (Storyteller of Oyo)",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
    authorBio: "Yoruba traditional archivist, playwright, and narrator of coastal legends.",
    publishedAt: "Mar 01, 2026",
    updatedAt: "Mar 05, 2026",
    estimatedReadTime: 15,
    totalChapters: 2,
    totalBranches: 10,
    readsCount: 16200,
    likesCount: 1410,
    bookmarksCount: 620,
    favoritesCount: 780,
    commentsCount: 88,
    isFeatured: false,
    isRecentlyUpdated: true,
    isNewRelease: true,
    isInteractive: true,
    hasAudioNarration: false,
  },
  {
    id: "dogon-sirius-star-dancers",
    slug: "dogon-sirius-star-dancers",
    aliases: ["hr-5", "dogon-1"],
    title: "The Sirius Star Dancers of Dogon",
    subtitle: "Cosmology and Masked Sigui Rituals",
    synopsis: "Deep in the Bandiagara Escarpment, elder Oumar initiates a youth into the secret Sigui astronomical songs that mapped the white dwarf star centuries before telescopes were conceived.",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
    tradition: "Dogon",
    mainGenre: "Cosmology & Astronomy",
    subGenres: ["Rituals", "Bandiagara", "Afrofuturism"],
    tags: ["Dogon", "Sirius", "Sigui", "Mali", "Cosmology"],
    difficulty: "Elderly / Complex",
    status: "completed",
    authorId: "user-oumar-04",
    authorName: "Oumar Sangare",
    authorPenName: "Oumar Sangare the Astrologer",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
    authorBio: "Bandiagara escarpment scholar documenting ancient cliff architecture and star maps.",
    publishedAt: "Jan 25, 2026",
    updatedAt: "Feb 10, 2026",
    estimatedReadTime: 18,
    totalChapters: 4,
    totalBranches: 16,
    readsCount: 19800,
    likesCount: 1740,
    bookmarksCount: 710,
    favoritesCount: 890,
    commentsCount: 74,
    isFeatured: false,
    isRecentlyUpdated: false,
    isNewRelease: true,
    isInteractive: true,
    hasAudioNarration: true,
  },
  {
    id: "la-ciguapa-secrets-of-cordillera",
    slug: "la-ciguapa-secrets-of-cordillera",
    aliases: ["dr-1", "hr-6", "ciguapa-1", "la-ciguapa"],
    title: "La Ciguapa: Secrets of the Cordillera",
    subtitle: "The Wild Maiden with Feet Pointing Backward",
    synopsis: "Deep in the mist-shrouded pine forests of Jarabacoa, young Mateo encounters the legendary Ciguapa—a creature of raw nature and ancient Taíno spirits whose backward footprints lead seekers either to hidden wisdom or into the heart of the mountain.",
    coverImage: "https://images.unsplash.com/photo-1511497584788-876761c119ef?q=80&w=800&auto=format&fit=crop",
    tradition: "Dominican Republic",
    mainGenre: "Caribbean Folklore",
    subGenres: ["Mountain Legends", "Taíno Heritage", "Mythology"],
    tags: ["DominicanRepublic", "Ciguapa", "Cordillera", "Taino", "Jarabacoa", "Quisqueya"],
    difficulty: "Intermediate",
    status: "completed",
    authorId: "user-mateo-dr",
    authorName: "Mateo Rosario",
    authorPenName: "Mateo of Quisqueya",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
    authorBio: "Dominican folklorist and preserver of Taíno & Afro-Caribbean oral mythology across the Cordillera Central.",
    publishedAt: "Feb 28, 2026",
    updatedAt: "Mar 04, 2026",
    estimatedReadTime: 14,
    totalChapters: 2,
    totalBranches: 10,
    readsCount: 24150,
    likesCount: 2190,
    bookmarksCount: 830,
    favoritesCount: 960,
    commentsCount: 115,
    isFeatured: true,
    isRecentlyUpdated: true,
    isNewRelease: true,
    isInteractive: true,
    hasAudioNarration: true,
    chapters: [
      {
        id: "dr-chap-1",
        number: 1,
        title: "The Footprints in the Pine Needles",
        summary: "Mateo follows mysterious tracks pointing up mountain slopes, only to realize the traveler was moving downward.",
        readTimeMinutes: 5,
        status: "published",
        likesCount: 740,
        commentsCount: 38,
        updatedAt: "2026-02-28",
        rootNodeId: "dr-node-1",
        nodes: {
          "dr-node-1": {
            id: "dr-node-1",
            title: "The Mist of Jarabacoa",
            content: `The twilight air of Jarabacoa smelled of sweet pine resin and damp river clay. Mateo tightened the straps of his leather satchel, gazing down at the forest floor.

Distinct footprints indented the wet earth—toes pointing firmly up toward the highest peaks of the Cordillera Central. Yet the broken twigs and brushed ferns told a contradictory tale: whatever made these tracks was walking backwards, descending into the dark valley.

"La Ciguapa," whispered Mateo's uncle in memory. "She carries the wild memory of Quisqueya. Follow her toes and you wander into trap; follow her direction and you find her gaze."`,
            choices: [
              {
                id: "choice-dr-1a",
                label: "Follow the physical direction of movement (descend toward the river)",
                targetNodeId: "dr-node-2a",
                moralWeight: 2,
                consequenceHint: "Respects natural logic and heeds ancient hunter wisdom...",
              },
              {
                id: "choice-dr-1b",
                label: "Follow the direction the toes are pointing (ascend into the high pines)",
                targetNodeId: "dr-node-2b",
                moralWeight: -1,
                consequenceHint: "Chases the optical illusion up the steep crags...",
              },
            ],
          },
          "dr-node-2a": {
            id: "dr-node-2a",
            title: "The Whispering Falls of Yaque del Norte",
            content: `Following the physical path of bent ferns, Mateo reached the turquoise basin of the river. Crouched on a moss-covered boulder was a breathtaking figure—long, blue-black hair draping down past her ankles like a silk cloak, skin shimmering with river mist, and eyes wild yet ancient.

She turned her head, her gaze piercing Mateo's soul without speaking a single spoken word. In her hands, she held a glowing Taíno petroglyph stone.`,
            choices: [
              {
                id: "choice-dr-2a1",
                label: "Bow your head in sign of peace and offer a fresh guayaba fruit",
                targetNodeId: "dr-node-3a",
                moralWeight: 3,
                consequenceHint: "Demonstrates reverence for island spirits and nature...",
              },
              {
                id: "choice-dr-2a2",
                label: "Call out her name softly and ask for the mountain secret",
                targetNodeId: "dr-node-3b",
                moralWeight: 1,
                consequenceHint: "Direct approach risks startling the shy guardian...",
              },
            ],
          },
          "dr-node-2b": {
            id: "dr-node-2b",
            title: "Lost in the High Pine Canopies",
            content: `Climbing higher toward the cold peaks, Mateo found himself wrapped in thick mountain fog. The tracks disappeared into razor-sharp rocks. A soft, blue-black shadow darted high above the pine branches, laughing like a night bird.`,
            choices: [
              {
                id: "choice-dr-2b1",
                label: "Turn back toward the river stream sound",
                targetNodeId: "dr-node-2a",
                moralWeight: 1,
              },
            ],
          },
          "dr-node-3a": {
            id: "dr-node-3a",
            title: "The Gift of Quisqueya",
            isEnding: true,
            endingType: "triumph",
            moralLesson: "True understanding of nature requires looking beyond surface appearances and showing respect to the guardians of the land.",
            content: `La Ciguapa accepted the fruit with a gentle nod. She touched Mateo's forehead with the warm petroglyph stone, filling his mind with forgotten melodies of the Taíno caciques and the secret medicinal roots of the mountain.

She leapt effortlessly across the foaming waters, vanishing into the ferns—leaving Mateo with the wisdom to protect the Cordillera for generations to come.`,
            choices: [],
          },
          "dr-node-3b": {
            id: "dr-node-3b",
            title: "The Phantom of the Falls",
            isEnding: true,
            endingType: "mystery",
            moralLesson: "Some mysteries of the forest are meant to be observed with awe rather than captured with curiosity.",
            content: `At the sound of her name, La Ciguapa dove silently into the river basin without a splash. The waters rippled with golden light, leaving behind only a single glossy black feather and the scent of wild orchids.`,
            choices: [],
          },
        },
      },
    ],
  },
];

export const MOCK_CURRENT_USER: UserProfile = {
  id: "user-kwame-01",
  username: "kwame_asante",
  displayName: "Kwame Asante",
  penName: "Kwame of Ashanti",
  bio: "Keeper of Ashanti trickster lore and ancient Dogon constellation myths. Crafting multi-branch tales for the digital generation.",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
  country: "Ghana",
  role: "storyteller",
  traditionSpecialty: "Ashanti/Akan",
  createdAt: "2025-10-01",
  followersCount: 1420,
  followingCount: 89,
  onboardingCompleted: true,
  writingStats: {
    storiesPublished: 12,
    draftStories: 2,
    totalChaptersPublished: 28,
    totalReads: 38420,
    totalLikes: 2840,
    totalComments: 412,
  },
  readingStats: {
    booksRead: 19,
    chaptersRead: 64,
    readingStreakDays: 14,
    favoriteGenres: ["Trickster Lore", "Historical Epics", "Spiritual Lore"],
    interests: ["Oral Narration", "Branching Destinies", "Akan Philosophy"],
  },
  supportDetails: {
    paystackLink: "https://paystack.com/pay/kwame-asante",
    bankName: "Access Bank Plc",
    accountName: "Kwame Kofi Asante",
    accountNumber: "0123456789",
    isAcceptingSupport: true,
  },
  badges: [
    {
      id: "badge-1",
      name: "Spider Web Weaver",
      description: "Authored 5+ multi-branch interactive tales",
      iconName: "Sparkles",
      tier: "gold",
      unlockedAt: "2026-01-15",
    },
    {
      id: "badge-2",
      name: "Master Storyteller",
      description: "Reached 25,000 oral story listeners",
      iconName: "Volume2",
      tier: "elder",
      unlockedAt: "2026-03-20",
    },
    {
      id: "badge-3",
      name: "Baobab Guardian",
      description: "Preserved 10 historical folklore variations",
      iconName: "Trees",
      tier: "silver",
      unlockedAt: "2026-02-10",
    },
  ],
  socialLinks: {
    twitter: "https://twitter.com/kwame_asante",
    website: "https://inkoma.org/@kwame_asante",
  },
};

export const MOCK_SAVED_QUOTES: SavedQuote[] = [
  {
    id: "quote-1",
    storyId: "anansi-and-the-pot-of-wisdom",
    storyTitle: "Anansi and the Pot of Wisdom",
    chapterNumber: 1,
    chapterTitle: "The Calabash of All Wisdom",
    authorPenName: "Kwame of Ashanti",
    quoteText: "Wisdom is like water; it nourishes only when it flows freely across all the four winds.",
    savedAt: "2026-03-02",
  },
  {
    id: "quote-2",
    storyId: "sundiata-the-lion-king-of-mali",
    storyTitle: "Sundiata: The Lion King of Mali",
    chapterNumber: 1,
    chapterTitle: "The Iron Rod of Niani",
    authorPenName: "Amina of Djenné",
    quoteText: "The tree does not fear the tempest when its roots draw strength from the prayers of its ancestors.",
    savedAt: "2026-03-04",
  },
];

export const MOCK_READING_PROGRESS: ReadingProgress[] = [
  {
    storyId: "anansi-and-the-pot-of-wisdom",
    storyTitle: "Anansi and the Pot of Wisdom",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    authorPenName: "Kwame of Ashanti",
    lastChapterId: "chap-1",
    lastChapterNumber: 1,
    lastChapterTitle: "The Calabash of All Wisdom",
    progressPercentage: 65,
    lastReadAt: "2 hours ago",
  },
  {
    storyId: "sundiata-the-lion-king-of-mali",
    storyTitle: "Sundiata: The Lion King of Mali",
    coverImage: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?q=80&w=800&auto=format&fit=crop",
    authorPenName: "Amina of Djenné",
    lastChapterId: "sun-chap-1",
    lastChapterNumber: 1,
    lastChapterTitle: "The Iron Rod of Niani",
    progressPercentage: 30,
    lastReadAt: "Yesterday",
  },
];


